version: '3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    container_name: mysql
    environment:
      MYSQL_DATABASE: examv2thouraya
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: asijee
      MYSQL_ROOT_PASSWORD: asijee

    ports:
      - 3306:3306
    expose:
      - 3306
  prom_mysql_exporter:
    image: prom/mysqld-exporter
    links:
      - mysql
    ports:
      - '9104:9104'
    environment:
      DATA_SOURCE_NAME: root:asijee@(mysql:3306)/examv2thouraya
    command: /bin/mysqld_exporter collect.binlog_size=true collect.info_schema.processlist=true

  spring-back:
    image: koussayheni/exam:latest
    container_name: exam
    ports:
      - 8083:8083
    depends_on:
      - mysql
    expose:
      - 8083
